import Head from "next/head";
import HeaderBanner from "../components/headerBanner/headerBanner";
import Header from "../components/header/header";
import HeaderMenu from "../components/headerMenu/headerMenu";
import UspStrip from "../components/uspStrip/uspStrip";
import ShopBrands from "../components/shopBrands/shopBrands";
import Offers from "../components/offers/offers";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hamilton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderBanner />
      <Header />
      <HeaderMenu />
      <UspStrip />
      <ShopBrands />
      <Offers />
    </>
  );
}
